version: '3.8'
services:
  db:
    container_name: bingo_db
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password_segura" 
      MYSQL_DATABASE: bingo_db
      MYSQL_USER: bingo_app_user
      MYSQL_PASSWORD: "1234" 
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      
  backend:
    build: ./bingo-backend # Ruta a la carpeta de tu Spring Boot
    container_name: bingo_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bingo_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=bingo_app_user
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  frontend:
    build: ./bingo-frontend
    container_name: bingo_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./bingo-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - db